import type { Knex } from 'knex';

export async function seed(knex: Knex): Promise<void> {
  // Clear existing achievements and triggers
  await knex('achievement_triggers').del();
  await knex('achievements').del();

  // Insert predefined achievements
  const achievements = await knex('achievements').insert([
    // ===== BEGINNER ACHIEVEMENTS (Common) =====
    {
      title: 'Первая чашка',
      description: 'Завершите свой первый урок',
      condition_type: 'lessons_count',
      condition_value: 1,
      icon: '☕',
      rarity: 'common',
      xp_reward: 50,
      progress_total: 1,
      category: 'general',
    },
    {
      title: 'Начало пути',
      description: 'Завершите 5 уроков',
      condition_type: 'lessons_count',
      condition_value: 5,
      icon: '🎯',
      rarity: 'common',
      xp_reward: 100,
      progress_total: 5,
      category: 'general',
    },
    {
      title: 'Первый тест',
      description: 'Пройдите любой тест',
      condition_type: 'quizzes_count',
      condition_value: 1,
      icon: '📝',
      rarity: 'common',
      xp_reward: 50,
      progress_total: 1,
      category: 'general',
    },

    // ===== LESSON-SPECIFIC ACHIEVEMENTS =====
    {
      title: 'Знаток эспрессо',
      description: 'Изучите основы приготовления эспрессо',
      condition_type: 'lesson_complete',
      condition_value: 1, // Будет связано с конкретным уроком через triggers
      icon: '☕',
      rarity: 'common',
      xp_reward: 75,
      progress_total: 1,
      category: 'coffee_basics',
    },
    {
      title: 'Мастер капучино',
      description: 'Освойте искусство приготовления капучино',
      condition_type: 'lesson_complete',
      condition_value: 1,
      icon: '🥛',
      rarity: 'rare',
      xp_reward: 150,
      progress_total: 1,
      category: 'coffee_advanced',
    },
    {
      title: 'Латте-арт художник',
      description: 'Изучите технику латте-арт',
      condition_type: 'lesson_complete',
      condition_value: 1,
      icon: '🎨',
      rarity: 'epic',
      xp_reward: 300,
      progress_total: 1,
      category: 'coffee_art',
    },
    {
      title: 'Гуру обслуживания',
      description: 'Изучите основы клиентского сервиса',
      condition_type: 'lesson_complete',
      condition_value: 1,
      icon: '🤝',
      rarity: 'rare',
      xp_reward: 200,
      progress_total: 1,
      category: 'service',
    },

    // ===== MASTERY ACHIEVEMENTS (Rare) =====
    {
      title: 'Идеальный эспрессо',
      description: 'Получите 100% в любом тесте',
      condition_type: 'quiz_perfect',
      condition_value: 1,
      icon: '💯',
      rarity: 'rare',
      xp_reward: 200,
      progress_total: 1,
      category: 'mastery',
    },
    {
      title: 'Бариста-новичок',
      description: 'Завершите 10 уроков',
      condition_type: 'lessons_count',
      condition_value: 10,
      icon: '🎓',
      rarity: 'rare',
      xp_reward: 250,
      progress_total: 10,
      category: 'mastery',
    },
    {
      title: 'Знаток кофе',
      description: 'Завершите 25 уроков',
      condition_type: 'lessons_count',
      condition_value: 25,
      icon: '📚',
      rarity: 'rare',
      xp_reward: 500,
      progress_total: 25,
      category: 'mastery',
    },

    // ===== STREAK ACHIEVEMENTS (Rare/Epic) =====
    {
      title: 'Горячая серия',
      description: 'Учитесь 7 дней подряд',
      condition_type: 'streak_days',
      condition_value: 7,
      icon: '🔥',
      rarity: 'rare',
      xp_reward: 300,
      progress_total: 7,
      category: 'general',
    },
    {
      title: 'Несгибаемый',
      description: 'Учитесь 30 дней подряд',
      condition_type: 'streak_days',
      condition_value: 30,
      icon: '💪',
      rarity: 'epic',
      xp_reward: 1000,
      progress_total: 30,
      category: 'general',
    },

    // ===== SPEED ACHIEVEMENTS (Rare) =====
    {
      title: 'Быстрый старт',
      description: 'Завершите 5 уроков за один день',
      condition_type: 'lessons_in_day',
      condition_value: 5,
      icon: '⚡',
      rarity: 'rare',
      xp_reward: 300,
      progress_total: 5,
      category: 'speed',
    },
    {
      title: 'Снайпер',
      description: 'Пройдите тест на 100% с первой попытки',
      condition_type: 'quiz_perfect_first_try',
      condition_value: 1,
      icon: '🎯',
      rarity: 'rare',
      xp_reward: 250,
      progress_total: 1,
      category: 'speed',
    },

    // ===== PERSISTENCE ACHIEVEMENTS (Rare) =====
    {
      title: 'Не сдаюсь',
      description: 'Пройдите сложный тест после 3+ попыток',
      condition_type: 'quiz_passed_after_retries',
      condition_value: 3,
      icon: '🛡️',
      rarity: 'rare',
      xp_reward: 200,
      progress_total: 1,
      category: 'general',
    },
    {
      title: 'Перфекционист',
      description: 'Пересдайте тест для улучшения результата',
      condition_type: 'quiz_retake_improve',
      condition_value: 1,
      icon: '🔄',
      rarity: 'rare',
      xp_reward: 150,
      progress_total: 1,
      category: 'general',
    },

    // ===== SOCIAL ACHIEVEMENTS (Epic) =====
    {
      title: 'Топ-3 в рейтинге',
      description: 'Войдите в топ-3 по своей должности',
      condition_type: 'ranking_top',
      condition_value: 3,
      icon: '🥉',
      rarity: 'epic',
      xp_reward: 500,
      progress_total: 1,
      category: 'social',
    },
    {
      title: 'Лидер месяца',
      description: 'Станьте первым в рейтинге',
      condition_type: 'ranking_top',
      condition_value: 1,
      icon: '🏆',
      rarity: 'epic',
      xp_reward: 1000,
      progress_total: 1,
      category: 'social',
    },

    // ===== LEGENDARY ACHIEVEMENTS =====
    {
      title: 'Мастер кофе',
      description: 'Завершите 50 уроков',
      condition_type: 'lessons_count',
      condition_value: 50,
      icon: '🌟',
      rarity: 'epic',
      xp_reward: 1500,
      progress_total: 50,
      category: 'mastery',
    },
    {
      title: 'Легенда кофейни',
      description: 'Завершите 100 уроков',
      condition_type: 'lessons_count',
      condition_value: 100,
      icon: '👑',
      rarity: 'legendary',
      xp_reward: 5000,
      progress_total: 100,
      category: 'mastery',
    },
    {
      title: 'Гуру тестов',
      description: 'Получите 100% в 10 тестах',
      condition_type: 'quiz_perfect_count',
      condition_value: 10,
      icon: '🎓',
      rarity: 'legendary',
      xp_reward: 3000,
      progress_total: 10,
      category: 'mastery',
    },

    // ===== SECRET ACHIEVEMENTS =====
    {
      title: 'Полуночник',
      description: 'Завершите урок после 23:00',
      condition_type: 'lesson_late_night',
      condition_value: 1,
      icon: '🌙',
      rarity: 'rare',
      xp_reward: 100,
      progress_total: 1,
      category: 'special',
      is_secret: true,
    },
    {
      title: 'Ранняя пташка',
      description: 'Завершите урок до 7:00',
      condition_type: 'lesson_early_morning',
      condition_value: 1,
      icon: '🌅',
      rarity: 'rare',
      xp_reward: 100,
      progress_total: 1,
      category: 'special',
      is_secret: true,
    },
    {
      title: 'Марафонец',
      description: 'Учитесь 100 дней подряд',
      condition_type: 'streak_days',
      condition_value: 100,
      icon: '🏃',
      rarity: 'legendary',
      xp_reward: 5000,
      progress_total: 100,
      category: 'special',
      is_secret: true,
    },
  ]).returning('*');

  // Создаем триггеры для достижений, связанных с уроками
  // Примечание: В реальном проекте эти связи будут создаваться через админку
  console.log('✅ Achievements seeded successfully');
  console.log('📝 Note: Lesson-specific achievement triggers should be configured via admin panel');
}
